### PR TITLE
Fixed the issue and Added some test cases for widget section.

### PR DESCRIPTION
**Pull request by vineetasharma**

### CODE REVIEW

**Comment by RJASeoud** [comment]
Hi Daniel request to merge this request when available.

Thanks!

**Comment by RJASeoud** [comment]
Hi @DanielHindi  can you accept pull request

**Comment by DanielHindi** [comment]
there are conflicts

**Comment by vineetasharma** [comment]
Hi @DanielHindi  Resolved the conflicts, Please merge now.

**Pull request merged**
